#-------------------------------------------------
#   File Name：     storeManager
#   Description :
#   Author :        Meiyo
#   date：          2019/10/9 10:33
#-------------------------------------------------
#   Change Activity:
#                   2019/10/9:
#------------------------------------------------- 
ShopManagerInfo:
    merchantcode: 
    usercode: 
    password: 

CashierInfo:
    merchantcode: 
    usercode: 
    password: 
